# www.github.com/GiacomoPinardi/project-euler

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Main

result = 0
fib_old = 1
fib_new = 1

while fib_new <= 4000000:
    fib_old, fib_new = fib_new, fib_new + fib_old

    if fib_new%2 == 0:
        result += fib_new

print result

#
